"""add_tg_bind_codes_table

Revision ID: c0a46cb4cea9
Revises: a7a440f91f67
Create Date: 2026-09-03 13:40:31.989385

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a46cb4cea9'
down_revision: Union[str, None] = 'a7a440f91f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tg_bind_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['consumed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tg_bind_codes_code'), 'tg_bind_codes', ['code'], unique=True)
    op.create_index(op.f('ix_tg_bind_codes_expires_at'), 'tg_bind_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tg_bind_codes_id'), 'tg_bind_codes', ['id'], unique=False)
    op.create_index(op.f('ix_tg_bind_codes_tg_user_id'), 'tg_bind_codes', ['tg_user_id'], unique=False)
    op.create_index('uq_tg_bind_active_code', 'tg_bind_codes', ['tg_user_id'], unique=True, postgresql_where=sa.text('consumed_at IS NULL'), sqlite_where=sa.text('consumed_at IS NULL'))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tg_bind_active_code', table_name='tg_bind_codes', postgresql_where=sa.text('consumed_at IS NULL'), sqlite_where=sa.text('consumed_at IS NULL'))
    op.drop_index(op.f('ix_tg_bind_codes_tg_user_id'), table_name='tg_bind_codes')
    op.drop_index(op.f('ix_tg_bind_codes_id'), table_name='tg_bind_codes')
    op.drop_index(op.f('ix_tg_bind_codes_expires_at'), table_name='tg_bind_codes')
    op.drop_index(op.f('ix_tg_bind_codes_code'), table_name='tg_bind_codes')
    op.drop_table('tg_bind_codes')
    # ### end Alembic commands ###
