"""add_estimated_reward_points

Revision ID: d66ba7fe9bfb
Revises: f45f58b6aa07
Create Date: 2026-09-02 14:45:00.803880

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66ba7fe9bfb'
down_revision: Union[str, None] = 'f45f58b6aa07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('estimated_reward_points', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'estimated_reward_points')
    # ### end Alembic commands ###
