"""production_full_schema

Revision ID: 20c3902e4dac
Revises: 
Create Date: 2026-09-02 11:54:42.519094

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c3902e4dac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('shop_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('fulfillment_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_items_id'), 'shop_items', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('emby_user_id', sa.String(length=128), nullable=True),
    sa.Column('emby_username', sa.String(length=64), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sign_in_streak', sa.Integer(), nullable=False),
    sa.Column('last_sign_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_emby_user_id'), 'users', ['emby_user_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('media_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('overview', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_items_count', sa.Integer(), nullable=False),
    sa.Column('accepted_items_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id', 'media_type', name='uq_media_task_tmdb_type')
    )
    op.create_index(op.f('ix_media_tasks_id'), 'media_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_media_tasks_media_type'), 'media_tasks', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_tasks_status'), 'media_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_media_tasks_title'), 'media_tasks', ['title'], unique=False)
    op.create_index(op.f('ix_media_tasks_tmdb_id'), 'media_tasks', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_media_tasks_year'), 'media_tasks', ['year'], unique=False)
    op.create_table('points_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=True),
    sa.Column('ref_id', sa.String(length=128), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_ledger_created_at'), 'points_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_points_ledger_event_type'), 'points_ledger', ['event_type'], unique=False)
    op.create_index(op.f('ix_points_ledger_id'), 'points_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_points_ledger_idempotency_key'), 'points_ledger', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_points_ledger_user_id'), 'points_ledger', ['user_id'], unique=False)
    op.create_table('shop_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delivery_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['shop_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_orders_id'), 'shop_orders', ['id'], unique=False)
    op.create_index(op.f('ix_shop_orders_item_id'), 'shop_orders', ['item_id'], unique=False)
    op.create_index(op.f('ix_shop_orders_status'), 'shop_orders', ['status'], unique=False)
    op.create_index(op.f('ix_shop_orders_user_id'), 'shop_orders', ['user_id'], unique=False)
    op.create_table('sign_in_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sign_date', sa.Date(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sign_date', name='uq_user_sign_date')
    )
    op.create_index(op.f('ix_sign_in_records_id'), 'sign_in_records', ['id'], unique=False)
    op.create_index(op.f('ix_sign_in_records_user_id'), 'sign_in_records', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('magnet_uri', sa.Text(), nullable=False),
    sa.Column('torrent_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['media_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_index(op.f('ix_submissions_tmdb_id'), 'submissions', ['tmdb_id'], unique=False)
    op.create_index(op.f('ix_submissions_torrent_hash'), 'submissions', ['torrent_hash'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_table('task_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reserved_by', sa.Integer(), nullable=True),
    sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_submission_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['reserved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['media_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_items_id'), 'task_items', ['id'], unique=False)
    op.create_index(op.f('ix_task_items_status'), 'task_items', ['status'], unique=False)
    op.create_index(op.f('ix_task_items_task_id'), 'task_items', ['task_id'], unique=False)
    op.create_index('uq_task_item_episode', 'task_items', ['task_id', 'season', 'episode'], unique=True, postgresql_where=sa.text('season IS NOT NULL AND episode IS NOT NULL'), sqlite_where=sa.text('season IS NOT NULL AND episode IS NOT NULL'))
    op.create_index('uq_task_item_movie', 'task_items', ['task_id'], unique=True, postgresql_where=sa.text('season IS NULL AND episode IS NULL'), sqlite_where=sa.text('season IS NULL AND episode IS NULL'))
    op.create_table('download_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('torrent_hash', sa.String(length=64), nullable=False),
    sa.Column('save_path', sa.Text(), nullable=True),
    sa.Column('content_path', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('download_speed', sa.BigInteger(), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('downloaded_bytes', sa.BigInteger(), nullable=True),
    sa.Column('last_progress_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_id'), 'download_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_download_jobs_submission_id'), 'download_jobs', ['submission_id'], unique=True)
    op.create_index(op.f('ix_download_jobs_torrent_hash'), 'download_jobs', ['torrent_hash'], unique=False)
    op.create_table('submission_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_item_id', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('dest_file', sa.Text(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('video_codec', sa.String(length=32), nullable=True),
    sa.Column('audio_codec', sa.String(length=32), nullable=True),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('is_4k', sa.Boolean(), nullable=True),
    sa.Column('raw_qc_json', sa.Text(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['media_tasks.id'], ),
    sa.ForeignKeyConstraint(['task_item_id'], ['task_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_items_id'), 'submission_items', ['id'], unique=False)
    op.create_index(op.f('ix_submission_items_status'), 'submission_items', ['status'], unique=False)
    op.create_index(op.f('ix_submission_items_submission_id'), 'submission_items', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submission_items_task_id'), 'submission_items', ['task_id'], unique=False)
    op.create_index(op.f('ix_submission_items_task_item_id'), 'submission_items', ['task_item_id'], unique=False)
    op.create_index('uq_accepted_episode_item', 'submission_items', ['task_id', 'season', 'episode'], unique=True, postgresql_where=sa.text("status = 'accepted' AND media_type != 'movie'"), sqlite_where=sa.text("status = 'accepted' AND media_type != 'movie'"))
    op.create_index('uq_accepted_movie_item', 'submission_items', ['task_id'], unique=True, postgresql_where=sa.text("status = 'accepted' AND media_type = 'movie'"), sqlite_where=sa.text("status = 'accepted' AND media_type = 'movie'"))
    op.create_table('wanted_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('bounty_points', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('claimant_id', sa.Integer(), nullable=True),
    sa.Column('submission_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['claimant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_item_id'], ['submission_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wanted_exact_target', 'wanted_tasks', ['tmdb_id', 'media_type', 'season', 'episode'], unique=False)
    op.create_index(op.f('ix_wanted_tasks_creator_id'), 'wanted_tasks', ['creator_id'], unique=False)
    op.create_index(op.f('ix_wanted_tasks_id'), 'wanted_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_wanted_tasks_status'), 'wanted_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_wanted_tasks_tmdb_id'), 'wanted_tasks', ['tmdb_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wanted_tasks_tmdb_id'), table_name='wanted_tasks')
    op.drop_index(op.f('ix_wanted_tasks_status'), table_name='wanted_tasks')
    op.drop_index(op.f('ix_wanted_tasks_id'), table_name='wanted_tasks')
    op.drop_index(op.f('ix_wanted_tasks_creator_id'), table_name='wanted_tasks')
    op.drop_index('idx_wanted_exact_target', table_name='wanted_tasks')
    op.drop_table('wanted_tasks')
    op.drop_index('uq_accepted_movie_item', table_name='submission_items', postgresql_where=sa.text("status = 'accepted' AND media_type = 'movie'"), sqlite_where=sa.text("status = 'accepted' AND media_type = 'movie'"))
    op.drop_index('uq_accepted_episode_item', table_name='submission_items', postgresql_where=sa.text("status = 'accepted' AND media_type != 'movie'"), sqlite_where=sa.text("status = 'accepted' AND media_type != 'movie'"))
    op.drop_index(op.f('ix_submission_items_task_item_id'), table_name='submission_items')
    op.drop_index(op.f('ix_submission_items_task_id'), table_name='submission_items')
    op.drop_index(op.f('ix_submission_items_submission_id'), table_name='submission_items')
    op.drop_index(op.f('ix_submission_items_status'), table_name='submission_items')
    op.drop_index(op.f('ix_submission_items_id'), table_name='submission_items')
    op.drop_table('submission_items')
    op.drop_index(op.f('ix_download_jobs_torrent_hash'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_submission_id'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_id'), table_name='download_jobs')
    op.drop_table('download_jobs')
    op.drop_index('uq_task_item_movie', table_name='task_items', postgresql_where=sa.text('season IS NULL AND episode IS NULL'), sqlite_where=sa.text('season IS NULL AND episode IS NULL'))
    op.drop_index('uq_task_item_episode', table_name='task_items', postgresql_where=sa.text('season IS NOT NULL AND episode IS NOT NULL'), sqlite_where=sa.text('season IS NOT NULL AND episode IS NOT NULL'))
    op.drop_index(op.f('ix_task_items_task_id'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_status'), table_name='task_items')
    op.drop_index(op.f('ix_task_items_id'), table_name='task_items')
    op.drop_table('task_items')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_torrent_hash'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_tmdb_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_sign_in_records_user_id'), table_name='sign_in_records')
    op.drop_index(op.f('ix_sign_in_records_id'), table_name='sign_in_records')
    op.drop_table('sign_in_records')
    op.drop_index(op.f('ix_shop_orders_user_id'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_status'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_item_id'), table_name='shop_orders')
    op.drop_index(op.f('ix_shop_orders_id'), table_name='shop_orders')
    op.drop_table('shop_orders')
    op.drop_index(op.f('ix_points_ledger_user_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_idempotency_key'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_id'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_event_type'), table_name='points_ledger')
    op.drop_index(op.f('ix_points_ledger_created_at'), table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index(op.f('ix_media_tasks_year'), table_name='media_tasks')
    op.drop_index(op.f('ix_media_tasks_tmdb_id'), table_name='media_tasks')
    op.drop_index(op.f('ix_media_tasks_title'), table_name='media_tasks')
    op.drop_index(op.f('ix_media_tasks_status'), table_name='media_tasks')
    op.drop_index(op.f('ix_media_tasks_media_type'), table_name='media_tasks')
    op.drop_index(op.f('ix_media_tasks_id'), table_name='media_tasks')
    op.drop_table('media_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_emby_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_shop_items_id'), table_name='shop_items')
    op.drop_table('shop_items')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
